### ISSUE TITLE
[BUG] Cannot receive ckETH

### ISSUE THREAD

**Issue by ThomasDang93** [dfinity/oisy-wallet#1999]
**Describe the bug**
When I click the Receive button for ckETH, I get blocked by the following error message.
```
Error while enabling the Erc20 twin token. / Invalid record {decimals:opt nat8; version:opt nat64; enabled:opt bool; chain_id:nat64; contract_address:text; symbol:opt text} argument: field contract_address -> Invalid text argument: undefined
```

**To Reproduce**

1. On the wallet home page, click ck Ethereum.
2. Click on the button labeled "Receive"
3. The error will show up on the button click.

**Expected behavior**
I was expecting a modal to pop up showing the ckETH address.

**Screenshots**
<img width="1762" alt="Screenshot 2024-08-11 at 10 48 00 PM" src="https://github.com/user-attachments/assets/52f38115-6e6d-4c1b-b846-7bb723d68b7f">

**Desktop (please complete the following information):**

- OS: macOS Sonoma 15.4
- Browser: Chrome
- Browser Version: 127.0.6533.100

**Comment by peterpeterparker** [comment]
Thanks! The fix will be deployed today.
