### ISSUE TITLE
Inquiry on Wallet Connection Feature for Mobile Apps

### ISSUE THREAD

**Issue by IhsotasTon** [dfinity/oisy-wallet#2009]
Hi Team,

I hope you’re doing well! I wanted to follow up regarding the timeline for the overall product to enter production, as well as when we can expect support for mobile apps.

Could you provide any updates on these two points? This information would be very helpful for our planning and development.

Thank you for your assistance, and I look forward to your response!

Best

**Comment by anedos-dfinity** [comment]
Hi @IhsotasTon , thanks for taking an interest in Oisy, there is no concrete timeline that we can give you, but I would say production-readiness is still 1-2 months away. As for mobile apps, that is not something we are considering right now, the premise of Oisy is to be web-based, so we want to make Oisy supremely usable in mobile browsers for now.

Hope that helps
