### ISSUE TITLE
How Oisy wallet generate ETH address?

### ISSUE THREAD

**Issue by baolongt** [dfinity/oisy-wallet#2038]
I'm looking for the part, Oisy wallet generate ETH wallet.

**Comment by bradstevens1** [comment]
Did you get it already?

**Comment by baolongt** [comment]
> Did you get it already?

no

**Comment by bradstevens1** [comment]
You haven’t yet ?

**Comment by bradstevens1** [comment]
From what app are you trying to generate the ETH wallet?

**Comment by peterpeterparker** [comment]
> I'm looking for the part, Oisy wallet generate ETH wallet.

Oisy uses the [threshold ECDSA API ](https://internetcomputer.org/docs/current/developer-docs/smart-contracts/signatures/signing-messages-t-ecdsa#obtaining-public-keys) to derive an ETH address for the principal of the user.

In backend code the related exposed endpoint is [eth_address_of](https://github.com/dfinity/oisy-wallet/blob/899afd015be4da8d08b7e4941217d4d49e08ec38/src/backend/src/lib.rs#L245).
