### ISSUE TITLE
Integrate email login in (Google/Apple Account)

### ISSUE THREAD

**Issue by 0xkookoo** [dfinity/oisy-wallet#2096]
**Is your feature request related to a problem? Please describe.**
Some of my web2 users want to have a blockchain account/wallet, but they don't want to keep the recovery phrase themselves, that's why I encourage them to use oisy.com. 
However, they don't have an Internet Identity and they don't even want to understand it. They just want to keep it stupid and simple, use Google Account / Apple Account to login and receive the crypto assets.
I have shown them how can they do that use OpenChat and Bioniq, they are shocked by the simplicity those two applications bring to them.

Overall, I hope oisy.com can integrate email login (Google Account).

**Describe the solution you'd like**
I don't have a clear solution, but below are some materials for your referrences.
- NFID, they can sign up with both of email and Google Account, and using single/multi-device passkeys to later sign in. Even support 2FA and recovery phrase function. https://learn.nfid.one/
- Bioniq, they integrated with Web3Auth, can sign up both of email and Google Account, and bind Twitter/discord as social factor. https://web3auth.io/docs/what-is-web3auth?product=Plug%20and%20Play, https://bioniq.io/

<img width="1720" alt="image" src="https://github.com/user-attachments/assets/a0dd1107-8eb1-46d8-a096-c9ef184aaab2">

<img width="1379" alt="image" src="https://github.com/user-attachments/assets/120fd883-3f7f-4770-890f-6de25f5f9c58">

**Comment by anedos-dfinity** [comment]
Thanks for the enhancement request @0xkookoo and apologies for the late response.

We have certainly discussed these options, I'm pretty sure that medium-term we'll introduce additional authentication options for Oisy and possibly even allow Oisy to manage passkeys itself (as opposed through II).

Right now, it's all hands on deck to launch a successful and usable Oisy v1 but we are also working to reduce any sign-up and sign-in friction with Internet Identity, lots of things will be landing over the next few weeks, so we'd be very keen on your feedback then.

**Comment by StefanBerger-DFINITY** [comment]
Hi @0xkookoo, support for W2 authentication services is now officially on the Roadmap of Internet Identity (II). The feature is already in work and will be available with the next release (of II, now OISY).
See the II (and other) roadmaps here: https://internetcomputer.org/roadmap#Identity-Synchrotron
