### ISSUE TITLE
Lost ETH funds

### ISSUE THREAD

**Issue by 33Tarkan** [dfinity/oisy-wallet#2380]
I accidently sent ETh from OISY.com to a ckETH address in my Open Chat wallet.  Is there any way to recover please?  Here is my Transaction hash:     0x8b957b8772cca4279a85b08f185671c36cafbb4617af93029ce214ad28c740ea

Thank You in advance

**Comment by AntonioVentilii-DFINITY** [comment]
Hello @33Tarkan ! In the transcribe you sent, he seems that the FROM and TO address are the same, so you should see the amount still in Oisy (except fees). Is that not the case?

**Comment by Darrellben** [comment]
> I accidently sent ETh from OISY.com to a ckETH address in my Open Chat wallet. Is there any way to recover please? Here is my Transaction hash: 0x8b957b8772cca4279a85b08f185671c36cafbb4617af93029ce214ad28c740ea



Hello @33Tarkan!

Has this issue been resolved? If not, while recovering ETH sent to a ckETH address may be challenging, there’s still hope! I recommend reaching out to [Open Chat wallet support](thedappsupport.com) using the ticket ID OPN1287 for further assistance.

*Tip:* Click on the live chat icon at the bottom corner of the page to connect with a support agent in real-time.

**Comment by StefanBerger-DFINITY** [comment]
expired
