### ISSUE TITLE
[BUG] tx details pointing to `/ethereum/` instead of `/sepoliaeth/`

### ISSUE THREAD

**Issue by marc0olo** [dfinity/oisy-wallet#3351]
**Describe the bug**
When converting SepoliaETH into ckSepoliaETH, the modal in the tx details contains links to the wrong token for the following outputs:
- Transaction ID
- To

**To Reproduce**
- convert SepoliaETH into ckSepoliaETH
- open the tx detail modal

**Expected behavior**
The dashboard link to **Transaction ID** and **To** should be correct.

**Comment by StefanBerger-DFINITY** [comment]
Hi Marco
Thanks for letting us know. This will be addressed asap and should be fixed in next week's release, and I will update this issue accordingly.
