### ISSUE TITLE
[BUG] Can not access Wallet

### ISSUE THREAD

**Issue by StefanBerger-DFINITY** [dfinity/oisy-wallet#3391]
**Describe the bug**
see: https://x.com/T3kNoLogic/status/1854377924939710799?t=RlyGiq2U7e1Arl0HWVgQDw

I'm experiencing a BUG that is not allowing me to access my wallet.

**To Reproduce**
unknown

**Expected behavior**
Login should work

**Screenshots**
![image](https://github.com/user-attachments/assets/839c294d-574e-47a6-93d2-13e1b1accea2)
![image](https://github.com/user-attachments/assets/ff447bd2-2e56-4166-884c-bfb480514ff3)

**Desktop (please complete the following information):**
unknown

**Smartphone (please complete the following information):**
unknown

**Additional context**
unknown

**Comment by peterpeterparker** [comment]
Duplicate https://github.com/dfinity/oisy-wallet/issues/3390
