### ISSUE TITLE
[BUG] "An issue occurred while setting up your wallet for signing. You've been signed out."

### ISSUE THREAD

**Issue by noiseframe** [dfinity/oisy-wallet#3583]
**The error occurs at login II. I created a wallet earlier and everything worked fine. I even made an ICP deposit, but then I was kicked out of my wallet and got the message “An issue occurred while setting up your wallet for signing. You've been signed out.” When I log in again, I get to the step “Retrieving your public keys” and then I get kicked out of the system again. And so every time...**

**To Reproduce**

1. Go to 'https://oisy.com/'
2. Click on 'open or create'
3. see 'Retrieving your public keys'

**I think I need to see my wallet with my ICP balance.**

**Screenshots**
<img width="1439" alt="Снимок экрана 2024-11-15 в 16 51 48" src="https://github.com/user-attachments/assets/d3d03e12-b67a-4ec6-ba40-ce482d9897ae">
<img width="1413" alt="Снимок экрана 2024-11-15 в 16 42 53" src="https://github.com/user-attachments/assets/8aeb7f49-e9f8-4338-95e2-4df45bd42ea6">

**Desktop (please complete the following information):**

- OS: macOS 15.1 (24B83)
- Browser chrome
- Version 130.0.6723.117

**Comment by StefanBerger-DFINITY** [comment]
Hi @noiseframe. Please accept our apologies for this. We had an issue this early afternoon with one of the involved canisters running of cycled, which lead to these symptoms. We could fix it a short time after and should be working all fine again.
Please let us know if that'w not the case for you.
Thanks

**Comment by Elsonbastey** [comment]
> **The error occurs at login II. I created a wallet earlier and everything worked fine. I even made an ICP deposit, but then I was kicked out of my wallet and got the message “An issue occurred while setting up your wallet for signing. You've been signed out.” When I log in again, I get to the step “Retrieving your public keys” and then I get kicked out of the system again. And so every time...**
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'https://oisy.com/'
> 2. Click on 'open or create'
> 3. see 'Retrieving your public keys'
> 4. See error
> 
> **I think I need to see my wallet with my ICP balance.**
> 
> **Screenshots** <img alt="Снимок экрана 2024-11-15 в 16 51 48" width="1439" src="https://private-user-images.githubusercontent.com/85865394/386586757-d3d03e12-b67a-4ec6-ba40-ce482d9897ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3MDM5MTgsIm5iZiI6MTczMTcwMzYxOCwicGF0aCI6Ii84NTg2NTM5NC8zODY1ODY3NTctZDNkMDNlMTItYjY3YS00ZWM2LWJhNDAtY2U0ODJkOTg5N2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDIwNDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhM2FiOGU4Yzg4ZmE5NzUyNTAxODYyZDQzYjQ3MzMzOTg0NDhhNTA0OWMxNTczZTFlN2M2NGExOGU3ZDQxODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fOrKhnJ6_zHQxa8RBcg3--vIzo5rAvS2B2dk97GwaCA"> <img alt="Снимок экрана 2024-11-15 в 16 42 53" width="1413" src="https://private-user-images.githubusercontent.com/85865394/386586813-8aeb7f49-e9f8-4338-95e2-4df45bd42ea6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3MDM5MTgsIm5iZiI6MTczMTcwMzYxOCwicGF0aCI6Ii84NTg2NTM5NC8zODY1ODY4MTMtOGFlYjdmNDktZTlmOC00MzM4LTk1ZTItNGRmNDViZDQyZWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDIwNDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMWExMDg5YTk5YTkzODIzODNmOTU5ZTJhZjFlNzcwZWY4YjhjOTBjZGI4NWE2ODBmNjQ2Nzk0YmY0OTdmMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.l5OBXoUfa-k1jWaxiY0__W3j4K2AhiUK5aVgJ9QFAOw">
> 
> **Desktop (please complete the following information):**
> 
> * OS: macOS 15.1 (24B83)
> * Browser chrome
> * Version 130.0.6723.117


Hello @noiseframe 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID ICP903711
Please see the link below to our dedicated support line:
[ Oisy Wallet DApps Support Ticket Requests.](https://thedappsupport.com)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
