### ISSUE TITLE
Error while loading the transactions. / Call was returned undefined, but type [[object Object]].

### ISSUE THREAD

**Issue by ysyms** [dfinity/oisy-wallet#3706]
Repeatedly pops up: Error while loading the transactions. / Call was returned undefined, but type [[object Object]].
<img width="403" alt="Capture d’écran 2024-11-20 à 18 51 29" src="https://github.com/user-attachments/assets/9a95654c-6ff5-48ea-9f01-eceb72a71e26">

**Comment by peterpeterparker** [comment]
@ysyms I don't know the answer, pinged my colleagues. I also updated your screenshot to display only the error.

**Comment by peterpeterparker** [comment]
Thanks for reporting! The issue arises because the Index canister `5ithz-aqaaa-aaaaq-aaa4a-cai` of GHOST is out of cycles.

I don't have direct contact with them, so I asked my colleagues to reach out. As soon as they top up their canister, the issue will be resolved.

**Comment by StefanBerger-DFINITY** [comment]
Issue with the GHOST index seems resolved. As info, we are also working on improvements to not show transaction related errors on the main token list, and displaying such errors in a nicer way once the transactions should be loaded.
