### ISSUE TITLE
ICL token balance display error

### ISSUE THREAD

**Issue by ysyms** [dfinity/oisy-wallet#3738]
<img width="739" alt="image" src="https://github.com/user-attachments/assets/c7121eb0-6c0f-4394-8365-1c9d54daf546">
pid：2ty2s-7l7hy-bip6m-6uopk-aijjn-ltbnz-o4imj-7ctxz-26czl-sykgp-oqe
Already transferred ICL tokens to another wallet, but the balance is not refreshing correctly

**Comment by StefanBerger-DFINITY** [comment]
Hi @ysyms thanks for letting us know.
We'll try to reproduce the issue and deploy a fix if need be. I'll keep you updated on this.

**Comment by StefanBerger-DFINITY** [comment]
Hi @ysyms.
The index canister of the ICL token ran out of cycles yesterday, so inquiry calls failed. This led to the latest value not being updated. We informed their team and the canister is back up. Also we will improve the app to use the ledger canister as fallback if the index canister fails.
