### ISSUE TITLE
Using Only oisy-wallet-signer for Authenticated Canister Calls

### ISSUE THREAD

**Issue by megalinker** [dfinity/oisy-wallet#3750]
Hi everyone,

I’m not sure if this is the right place or the best way to ask, but I have a question regarding authenticated canister calls. Specifically, is it possible to perform authenticated canister calls using only the oisy-wallet-signer, similar to how I’ve used the classic AuthClient or NFID to generate an identity and an agent?

Any guidance or examples on how to achieve this would be greatly appreciated.

Thank you!

**Comment by peterpeterparker** [comment]
Hi,

OISY does not, at least currently, delegate sessions, but it does support [ICRC-49](https://github.com/dfinity/wg-identity-authentication/blob/main/topics/icrc_49_call_canister.md), which allows dApps to execute canister calls through the wallet.

My understanding is that the foundation generally recommends using [IdentityKit](https://www.identitykit.xyz/) for clients. It is compatible with React. If you are using another technology, you can implement the flow yourself by using the [signer-js](https://github.com/slide-computer/signer-js) library, which is used under the hood by this solution.

Alternatively, if none of the above fits your needs, you can also take a look at the [oisy-wallet-signer](https://github.com/dfinity/oisy-wallet-signer), which includes an opinionated client.

Hope that helps.
