### ISSUE TITLE
[BUG] USDT token not found or loading in UI

### ISSUE THREAD

**Issue by helionicp** [dfinity/oisy-wallet#3751]
![error](https://github.com/user-attachments/assets/ab7d7018-05dc-469b-8149-d63333c32dd9)

1. Go to '...'Error while loading the ERC20 contracts. / missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0x054B8f99D15cC5B35a42a926635977d62692F25b","data":"0x95d89b41","accessList":null}, error={"reason":"bad response","code":"SERVER_ERROR","status":403,"headers":{"content-length":"96","content-type":"application/json"},"body":"{\"jsonrpc\":\"2.0\",\"id\":43,\"error\":{\"code\":-32600,\"message\":\"project ID is temporarily disabled\"}}","requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x054b8f99d15cc5b35a42a926635977d62692f25b\",\"data\":\"0x95d89b41\"},\"latest\"],\"id\":43,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://mainnet.infura.io/v3/bb094b985d4444e08d1358697d22dbd5"}, code=CALL_EXCEPTION, version=providers/5.7.2)

**Comment by StefanBerger-DFINITY** [comment]
Hi @helionicp, so far I could not reproduce the problem, and USDT is loading fine for me.
Do you still see the token list, but without USDT? If so, please open the "Manage Tokens" (at the bottom of the list) modal and disable USDT. Then load the token list again. Then turn it back on again and load it again (the million times proved "turn it off and back on again" ;) )

<img width="598" alt="image" src="https://github.com/user-attachments/assets/2c1bb6e0-41d0-4059-9b0b-faee4a73a045">

**Comment by helionicp** [comment]
Ok, it's working now. Thank you so much.

**Comment by helionicp** [comment]
There is a centralized point of failure in your system, you will need to change infra for Ethereum to a more decentralized version.

**Comment by StefanBerger-DFINITY** [comment]
Hi @helionicp Thanks for confirming that it's working now, and for pointing out an important aspect that could and should be improved.
I will put this on the table in our planning meetings, so we can evaluate it and take next steps on it.
