### ISSUE TITLE
[BUG] ERC20 deposit to the new minter contract 0x18901044688D3756C35Ed2b36D93e6a5B8e00E68 failed

### ISSUE THREAD

**Issue by nai2283** [dfinity/oisy-wallet#3785]
Possibly due to that the new contract split the deposit  function into two differect functions - Deposit Erc20 and Deposit Eth, while Oisy is still using the single Deposit function call.

**Comment by StefanBerger-DFINITY** [comment]
Hi @nai2283, we will look into this right away, and will provide a fix as quickly as possible.
I'll get back to you with further infos shortly.

**Comment by peterpeterparker** [comment]
Thanks for the report @nai2283! I can reproduce. I reached out the team to figure out what's happening.

**Comment by peterpeterparker** [comment]
Good catch, it's indeed an inherited issue as we are loading the addresses automatically from the minter.
The cross-chain team is working on a fix 👉 https://forum.dfinity.org/t/cketh-a-canister-issued-ether-twin-token-on-the-ic/22819/227?u=peterparker

**Comment by peterpeterparker** [comment]
The issue was handled as an important incident and was resolved through proposal [134344](https://dashboard.internetcomputer.org/proposal/134344). I just tried to convert ETH -> ckETH in OISY and everything worked out. Thanks again for reporting the issue.
