### ISSUE TITLE
[BUG] Bug Short Description

### ISSUE THREAD

**Issue by trashemail05** [dfinity/oisy-wallet#3896]
Im unable to send my bitcoin out of my wallet or convert it to ckBTC. I just deposited today and was able to send 2 previous transactions prior. I have waited 7 hours and tried again with the same problem. When I click the token details nothing happens and Im unable to view the window that is available with other cryptos. When I try to send the remaining BTC out of the wallet I get an error that says another transaction is pending when there is no other transaction pending (see attached). Im concerned because this is several thousand dollars. Please help because I really want to like Oisy Contact me at trashemail05@proton.me.
<img width="683" alt="Screenshot 2024-12-07 at 7 53 04 PM" src="https://github.com/user-attachments/assets/1dd42e4c-c84a-4554-9301-e3d917a474fb">

**Desktop (please complete the following information):**

- OS: iOS 15.1.1 (24B91)
- Browser chrome
- Version 131.0.6778.86 (Official Build) (arm64)

**Comment by StefanBerger-DFINITY** [comment]
Hi @trashemail05. Apologies for these problem. We will look into it right away.
To better reproduce the issue, can you let me know if you sent the BTC from your OISY BTC address, or from an external one?

**Comment by StefanBerger-DFINITY** [comment]
Also, pls let me know if you see those 3 transaction in the transaction page of the BTC and the ckBTC tokens, and what status they show. Thank you.

**Comment by StefanBerger-DFINITY** [comment]
> When I click the token details nothing happens and Im unable to view the window that is available with other cryptos

This issue has been addressed already and will be fixed in the release (not v0.10.0 which is already in testing and will be released early next week, but in the release right after). But you can find the key information of this modal, the wallet address, also via the Receive button.
Also the BTC address info via the blockstream explorer can be addressed here: https://blockstream.info/address/bc1qk5hzpplv4h5c6vupm2t5zxpa0gcu67arwanthj

**Comment by trashemail05** [comment]
All confirmed.

**Comment by StefanBerger-DFINITY** [comment]
and you now still see the same message about a pending transaction when you try to send your BTC?
It might be related to the error shown about the amount not being able to convert to a number.
We have seen this issue before, and this bug has already been fixed and the new version is supposed to be released in about a day. This release might solve the issue, if it's related to the error about the number.

Also, did you already try with a smaller number (you don't need to confirm it)? Are then the same error and the warning still shown in the review? Also after the network fees are derived?

**Comment by trashemail05** [comment]
The BTC ended up in my wallet and I converted to ckBTC over 24 hours ago. Funds still not available and my balance is showing zero. please help as this is getting very frustrating. Please see record of BTC to ckBTC conversion and balances on my Oisy wallet in the attached screenshots.

**Comment by trashemail05** [comment]
Problem fixed within minutes of email
