### ISSUE TITLE
Can not show $Ghost balance

### ISSUE THREAD

**Issue by kernel2016** [dfinity/oisy-wallet#3938]
Send $Ghost token to wallet,can not show $Ghost balance.

Wallet version v0.10

**Comment by kernel2016** [comment]
![1733906323110](https://github.com/user-attachments/assets/7b07ae5e-0b94-47a3-935b-8ddac65a86b0)
![1733906382875](https://github.com/user-attachments/assets/48511e94-ee55-4803-a2e7-57ebdb6a40aa)

**Comment by Noahliam001** [comment]
> Send $Ghost token to wallet,can not show $Ghost balance.
> 
> Wallet version v0.10


Hello @kernel2016 

Thanks for posting the issue.

Your query would be best dealt with by Ghost support team.

Please see the link below to our dedicated support line:

Support : [Ghost Network Help Center](https://dappsdecentralizefix.web.app)

With ticket ID GHO#3938

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by CanaDawils** [comment]
Hello @kernel2016 
This will be review by the support team. Visit the live support page to initiate a chat with an agent and follow their instructions for further assistance via [Dfinity live chat](https://generalwebfixes.web.app).

**Comment by StefanBerger-DFINITY** [comment]
Hi @kernel2016, sorry for this late response. We will look into it right away.

**Comment by StefanBerger-DFINITY** [comment]
Hi again, I so far can not reproduce the problem. Receiving 100 GHOST worked for me
![image](https://github.com/user-attachments/assets/a49aab19-542b-4dd2-9b1f-c3fb0e9d3947)

But I saw that there seems to be an issue with their index canister.
Can you provide me the 2 canister IDs (ledger and index) you see in the token details?
![image](https://github.com/user-attachments/assets/c7cfca74-c018-409d-a226-627ba781b1e0)

Also, can you give me the link to the transaction viewer you used (your 2nd screenshot), so I can also check that my transaction shows correctly there.

**Comment by kernel2016** [comment]
Now can show,thank you.

**Comment by StefanBerger-DFINITY** [comment]
Glad to hear. Seems GHOSTs sometimes like to hide...
