### ISSUE TITLE
Some questions about Oisy Wallet and its distributed ECDSA signing

### ISSUE THREAD

**Issue by johnnynanjiang** [dfinity/oisy-wallet#587]
Hi Oisy Wallet,

Sorry for posting these questions as an issue, as there is no discussion area. Hope it is ok.

It is great to come across this wallet, as it's nature is well aligned with our vision, which is: open source, decentralized, distributed private keys.

Just have a couple of questions that need your help clarify.

1. What is the difference between Oisy's distributed ECDSA signing and MPC?

2. "distributed key-shares among dedicated ICP replica nodes", does it mean the key shares are managed by a certain group of dedicated ICP nodes? Or all the nodes within the entire network?

3. How does the distributed ECDSA signing code get released to the ICP nodes?

Thanks and regards,

**Comment by anedos-dfinity** [comment]
Hi JJ, thanks for getting in touch, answers inline.

> Hi Oisy Wallet,
> 
> Sorry for posting these questions as an issue, as there is no discussion area. Hope it is ok.
> 

No problem for posting questions here, short-term we'd probably switch to a dedicated forum tag (https://forum.dfinity.org/) for Oisy wallet questions.

> It is great to come across this wallet, as it's nature is well aligned with our vision, which is: open source, decentralized, distributed private keys.

Definitely, happy you reached-out.

> 
> Just have a couple of questions that need your help clarify.
> 
> 1. What is the difference between Oisy's distributed ECDSA signing and MPC?

IC's threshold signatures and MPC are conceptually the same. In IC, tBLS and tECDSA are embedded in the core protocol (e.g., https://internetcomputer.org/docs/current/references/ic-interface-spec/#ic-sign_with_ecdsa) , so every IC smart contract can use them, while MPC in most wallets is implemented at the application layer. There are pros and cons for each choice.

> 2. "distributed key-shares among dedicated ICP replica nodes", does it mean the key shares are managed by a certain group of dedicated ICP nodes? Or all the nodes within the entire network?

IC support shards (or subnets as they're called), so a more accurate description would be that all key shares in a subnet participate in the MPC. In other words, there's no election or rotation process to select a dedicated subset of ICP nodes.

> 3. How does the distributed ECDSA signing code get released to the ICP nodes?
> 

Since both tBLS and tECDSA is part of the core protocol, any code updates have to be voted on-chain by the NNS DAO that controls the IC.

Hope the above helps - do let us know if you have further questions and happy to jump on a call with you to further discuss,

Andronikos

> Thanks and regards,

**Comment by johnnynanjiang** [comment]
Thanks @anedos-dfinity for your prompt and detailed answers, they help a lot.

1. `IC's threshold signatures and MPC are conceptually the same. In IC, tBLS and tECDSA are embedded in the core protocol (e.g., https://internetcomputer.org/docs/current/references/ic-interface-spec/#ic-sign_with_ecdsa) , so every IC smart contract can use them, while MPC in most wallets is implemented at the application layer. There are pros and cons for each choice.`

That sounds great, I wonder if smart contract is the only way to invoke the code, or core protocol level code can be invoked via a IC SDK client through RPC?

2. `IC support shards (or subnets as they're called), so a more accurate description would be that all key shares in a subnet participate in the MPC. In other words, there's no election or rotation process to select a dedicated subset of ICP nodes.`

Thanks. Does that mean the nodes in the subnet have to all keep participated all the time in order to aggregate the key share signing outputs? How about scenarios like some nodes join or leave, is there a key share redundancy?

3. `Since both tBLS and tECDSA is part of the core protocol, any code updates have to be voted on-chain by the NNS DAO that controls the IC.`

Is there a link to the voting process and requirements (such as token staking)? Thanks.

Thanks and regards,
Johnny

**Comment by Dfinity-Bjoern** [comment]
> That sounds great, I wonder if smart contract is the only way to invoke the code, or core protocol level code can be invoked via a IC SDK client through RPC?

The API can only be invoked by a smart contract. Invoking the API has an associated cost in cycles, and only canisters (smart contracts) can hold and transfer cycles.

> Thanks. Does that mean the nodes in the subnet have to all keep participated all the time in order to aggregate the key share signing outputs? How about scenarios like some nodes join or leave, is there a key share redundancy?

There is always redundancy; no step in the protocol requires more than 2/3 of the parties to be around. When nodes join or leave the network, the keys are reshared according to the new membership. This happens automatically as soon as membership changes.

> 3. `Since both tBLS and tECDSA is part of the core protocol, any code updates have to be voted on-chain by the NNS DAO that controls the IC.`
> 
> Is there a link to the voting process and requirements (such as token staking)? Thanks.

The [page on governance](https://internetcomputer.org/how-it-works/network-nervous-system-nns/) should have some helpful information. The presentation linked in the page is already a bit older, but all the core principles are still the same.

**Comment by johnnynanjiang** [comment]
Thanks @Dfinity-Bjoern for the clarification, it is much more clear now, and I think ICP is well aligned with our vision for next generation crypto wallets.

We would dig more into it and see how we go and let you know.

Cheers @Dfinity-Bjoern @anedos-dfinity , the ICP open source community is efficient and friendly, appreciate it.
