### ISSUE TITLE
A question about `sign_with_ecdsa`

### ISSUE THREAD

**Issue by johnnynanjiang** [dfinity/oisy-wallet#838]
At https://github.com/dfinity/oisy-wallet/blob/main/src/backend/src/lib.rs#L7

```
use ic_cdk::api::management_canister::ecdsa::{
    ecdsa_public_key, sign_with_ecdsa, EcdsaCurve, EcdsaKeyId, EcdsaPublicKeyArgument,
    SignWithEcdsaArgument,
};
```

Is it possible to hook up some custom calls at this point `sign_with_ecdsa`, so that 3rd parties can do some extra work like suspicious address scan or other security checks?

E.g. when the user want to sign a transaction by calling `sign_with_ecdsa`, if there are some hooks exist, they would do security checks for the transaction, and `sign_with_ecdsa` only proceeds after they pass.

Thanks and regards

**Comment by peterpeterparker** [comment]
Thread appears to be inactive, so I'm closing this question. Feel free to ping me if it needs to be reopened.

**Comment by johnnynanjiang** [comment]
> Interesting idea, is there a reason why you'd want such a precondition as a hook to `sign_with_ecdsa` as opposed to just a check before you call it ?

Yes I can write code to check before calling `sign_with_ecdsa`.

The point I'm trying to make is that hooks would allow extensions and plugins to be possible, in term of architecture.
